// generated by @ng-toolkit/universal
    const port = process.env.PORT || 8080;
    const api = require('./server/routes/api');
    const server = require('./dis/server');
    server.app.use('/api',api);
    server.app.listen(port, () => {
        console.log("Listening on: http://localhost:" + port );
    });
    